### ISSUE TITLE
SQLite Error 26: 'file is not a database'

### ISSUE THREAD

**Issue by YDGeon0510** [nosyrbllewe/LLASDecryptor#7]
I tried to decrypt the files from the Japanese version of the game, and I keep getting this error message.

SQLite Error 26: 'file is not a database: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements (Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteCommand.GetStatements (Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
at LLASDecryptor.Core.DatabaseReader.GetRowsInTable(String table) in D:\a\LLASDecryptor\LLASDecryptor\LLASDecryptor.Core\DatabaseReader.cs:line 38
at LLASDecryptor.Core.Decryptor.DecryptFiles(Table[] tables) in D:\a\LLASDecryptor\LLASDecryptor\LLAS Decryptor.Core\Decryptor.cs:line 47
at LLASDecryptor.Interface.MainWindow.FileButton_Click(Object sender, RoutedEventArgs e) in D:\a\LLASDecryptor\LLASDecryptor\LLASDecryptor.Interface\MainWindow.xaml.cs:line 85

I don't know if I'm doing it right but I'm stuck here.

**Comment by nosyrbllewe** [comment]
Sorry for the delayed response. 
Unfortunately, I can't tell the issue from your error message. For instance, it could be the wrong path for the input files or that you are using the wrong decryption key.
